declare const styles: {
  readonly bottom__button: string;
  readonly bottom__button_container: string;
  readonly bottom__button_text: string;
  readonly bottom__tip: string;
  readonly button__fullWidth: string;
  readonly button_content: string;
  readonly container: string;
  readonly "custom-button": string;
  readonly editor: string;
  readonly isMore: string;
  readonly mid__column: string;
  readonly mid__column_icon_container: string;
  readonly mid__column_text: string;
  readonly mid__column_text_typography: string;
  readonly primary: string;
  readonly secondary: string;
  readonly top__column: string;
  readonly top__column_icon_container: string;
  readonly top__column_text: string;
  readonly top__column_textarea: string;
  readonly top__column_textarea_container: string;
  readonly "vibe-selector": string;
};
export = styles;
